---
- name: Main Playbook
  hosts: odscshe-pr.in.oracle.com
  vars_files:
    - password.yaml
  tasks:
    - name: Obtain SSO token with using username/password credentials
      ovirt_auth:
        url: https://odscshe-pr.in.oracle.com/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "{{ olvm_password }}"
    - name: Create Virtual Network
      ovirt_network:
        auth: "{{ ovirt_auth }}"        
        name: net_ansible
        state: present
        comment: network created through Ansible
        data_center: Default
        vm_network: yes
        clusters:
          - name: Default
            assigned: yes
            required: yes
    - name: Cleanup OLVM auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
