---
- name: Main Playbook
  hosts: odscshe-pr.in.oracle.com
  vars_files:
    - password.yaml
  tasks:
    - name: Obtain SSO token with using username/password credentials
      ovirt_auth:
        url: https://odscshe-pr.in.oracle.com/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "{{ olvm_password }}"
    - name: Detach Virtual disk from VM
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: data_disk_olam_dep
        state: detached
        vm_name: osmh-ravi
    - name: Delete Virtual disk
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: data_disk_olam_dep
        state: absent
