---
- name: Main Playbook
  hosts: odscshe-pr.in.oracle.com
  vars_files:
    - password.yaml
    - vm_name_list.yaml
  tasks:
    - name: Obtain SSO token with using username/password credentials
      ovirt.ovirt.ovirt_auth:
        url: https://odscshe-pr.in.oracle.com/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "{{ olvm_password }}"
    - name: Create Virtual Machine from Template
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "Default"
        template: OL8U10_x86_64-olvm-b237
        name: "{{ item.name }}"
        state: running
        high_availability: yes
        memory: 2GiB
        stateless: no
        cloud_init:
           host_name: "{{ item.hostname }}"
           user_name: root
           dns_servers: "{{ net_detail[1].dname }}"
           nic_name: "{{ vm_nicname | default('eth0') }}"
           nic_boot_protocol: static
           nic_ip_address: "{{ net_detail[1].ip_add}}"
           nic_gateway: "{{ net_detail[1].gateway }}"
           nic_netmask: "{{ net_detail[1].subnet }}"
           custom_script: |
             password: "{{ root_password }}"
             chpasswd: { expire: False }
             ssh_pwauth: True
             runcmd:
               - hostnamectl set-hostname "{{ item.name }}"
#               - touch /tmp/done
      loop: "{{ vms_list }}"      
    - name: Attach Network Profile
      ovirt_nic:
        auth: "{{ ovirt_auth }}"
        vm: "{{ item.name }}"
        name: nic1
        profile: ovirtmgmt
        network: ovirtmgmt
      loop: "{{ vms_list }}"  
    - name: Cleanup OLVM auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
