---
- name: Main Playbook
  hosts: odscshe-pr.in.oracle.com
  vars_files:
    - password.yaml
    - vm_name_list.yaml
  tasks:
    - name: Obtain SSO token with using username/password credentials
      ovirt.ovirt.ovirt_auth:
        url: https://odscshe-pr.in.oracle.com/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "{{ olvm_password }}"
    - name: Create Virtual Machine from Template
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "Default"
        template: OL8U10_x86_64-olvm-b237
        name: "{{ item }}"
        state: running
        high_availability: yes
        memory: 2GiB
        stateless: no
        cloud_init:
           host_name: olam_dep_net_test.in.oracle.com
           user_name: root
#           dns_servers: 206.223.27.1
#           nic_name: "{{ vm_nicname | default('eth0') }}"
           nic_boot_protocol: dhcp
#           nic_ip_address: 10.178.73.6
#           nic_gateway: 10.178.72.1
#           nic_netmask: 255.255.252.0  
           custom_script: |
             password: "{{ root_password }}"
             chpasswd: { expire: False }
             ssh_pwauth: True
#             runcmd:
#               - hostnamectl set-hostname olam_dep_net.in.oracle.com
#               - touch /tmp/done
      
    - name: Attach Network Profile
      ovirt_nic:
        auth: "{{ ovirt_auth }}"
        vm: olam_dep_net
        name: nic1
        profile: ovirtmgmt
        network: ovirtmgmt
    - name: Cleanup OLVM auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
loop: "{{ vms_list }}"
