---
- name: Main Playbook
  hosts: odscshe-pr.in.oracle.com
  vars_files:
    - password.yaml
  tasks:
    - name: Obtain SSO token with using username/password credentials
      ovirt.ovirt.ovirt_auth:
        url: https://odscshe-pr.in.oracle.com/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "{{ olvm_password }}"
    - name: Create Virtual Machine from Template
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "Default"
        template: ol8-template-latest
        name: "olam_dep"
        state: running
        high_availability: yes
        cloud_init:
           custom_script:
             runcmd:
               - hostnamectl set-hostname olam_dep.in.oracle.com
