---
- name: Main Playbook
  hosts: odscshe-pr.in.oracle.com
  vars_files:
    - password.yaml
  tasks:
    - name: Obtain SSO token with using username/password credentials
      ovirt.ovirt.ovirt_auth:
        url: https://odscshe-pr.in.oracle.com/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "{{ olvm_password }}"
    - name: Create Virtual Machine from Template
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "Default"
        template: OL8U10_x86_64-olvm-b237
        name: "olam_dep"
        state: running
        high_availability: yes
        cloud_init:
           host_name: olam_depin.oracle.com
           user_name: root
           root_password: monster
           nic_boot_protocol: dhcp
           nic_on_boot: true
        nics:
          - name: ovirtmgmt
            interface: virtio
            profile_name: ovirtmgmt
        memory: 2GiB
