---
- name: Main Playbook
  hosts: odscshe-pr.in.oracle.com
  vars_files:
    - password.yaml
  tasks:
    - name: Obtain SSO token with using username/password credentials
      ovirt.ovirt.ovirt_auth:
        url: https://odscshe-pr.in.oracle.com/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "{{ olvm_password }}"
    - name: Create Virtual Machine from Template
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "Default"
        template: OL8U10_x86_64-olvm-b237
        name: "olam_dep1"
        state: running
        high_availability: yes
        memory: 2GiB
        cloud_init:
           host_name: olam_dep1.in.oracle.com
           user_name: root
           nic_boot_protocol: dhcp
           custom_script: |
             password: "{{ root_password }}"
             chpasswd: { expire: False }
             ssh_pwauth: True
             runcmd:
               - hostnamectl set-hostname olam_dep1-run.in.oracle.com
               - touch /tmp/done
    - name: Get VM details
      ovirt.ovirt.ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        name: olam_dep1  # Replace with your VM name
      register: vm_info
    - name: Display attached NICs
      debug:
        msg: |
          Attached NICs for VM "{{ vm_info.vm.name }}":
          {% for nic in vm_info.vm.nics %}
            - NIC Name: {{ nic.name }}
              Network: {{ nic.network.name }}
              Interface: {{ nic.interface }}
          {% endfor %}           
    - name: Remove all attached NICs from the VM
      ovirt.ovirt.ovirt_nic:
        auth: "{{ ovirt_auth }}"
        state: absent
        vm: olam_dep1  # Replace with your VM name
      loop: "{{ vm_info.vm.nics }}"
      loop_control:
        label: "{{ item.name }}"
    - name: Add Nic
      ovirt_nic:
        auth: "{{ ovirt_auth }}"
        state: present
        vm: olam_dep1
        name: ovirtmgmt
        interface: virtio
        profile: ovirtmgmt
        network: ovirtmgmt
    - name: Reboot the VM to apply network changes
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        state: reboot
        name: olam_dep1     
