---
- name: Main Playbook
  hosts: odscshe-pr.in.oracle.com
  vars_files:
    - password.yaml
  tasks:
    - name: Obtain SSO token with using username/password credentials
      ovirt.ovirt.ovirt_auth:
        url: https://odscshe-pr.in.oracle.com/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "{{ olvm_password }}"
    - name: Create Virtual Machine from Template
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "Default"
        template: OL8U10_x86_64-olvm-b237
        name: "olam_dep_net"
        state: running
        high_availability: yes
        memory: 2GiB
        nics:
          - name: nic1
            interface: virtio
            profile: ovirtmgmt
        cloud_init:
           nic_boot_protocol: static
           nic_gateway: 10.178.72.1
           nic_ip_address: 10.178.73.6
           nic_netmask: 255.255.252.0
           dns_servers: 206.223.27.1
           nic_name: enp1s0
           nic_on_boot: yes
           host_name: olam_dep_net_test.in.oracle.com
           user_name: root
           custom_script: |
             password: "{{ root_password }}"
             chpasswd: { expire: False }
             ssh_pwauth: True
             runcmd:
               - hostnamectl set-hostname olam_dep_net.in.oracle.com
               - touch /tmp/done
# Half Backed             write_files:
#               - path: /etc/sysconfig/network-scripts/ifcfg-eth0
#                 content: |
#                   DEVICE=eth0
#                   BOOTPROTO=static
#                   ONBOOT=yes
#                   IPADDR=10.178.73.6
#                   NETMASK=255.255.252.0
#                   GATEWAY=10.178.72.1
#                   DNS1=206.223.27.1

#    - name: Add Nic
#      ovirt_nic:
#        auth: "{{ ovirt_auth }}"
#        state: present
#        vm: olam_dep_net
#        name: test
#        interface: virtio
#        profile: ovirtmgmt
#        network: ovirtmgmt      
#    - ovirt.ovirt.ovirt_nic_info:
#        auth: "{{ ovirt_auth }}"
#        vm: olam_dep_net
#        name: n*
#      register: result
#    - ansible.builtin.debug:
#        msg: |
#          Attached NICs for VM:
#          {% for nic in result.ovirt_nics %}
#            - NIC Name: {{ nic.name }}
#          {% endfor %}
#    - name: Delete NICs matching pattern
#      ovirt.ovirt.ovirt_nic:
#        auth: "{{ ovirt_auth }}"
#        vm: olam_dep_net
#        name: "{{ item.name }}"
#        state: absent
#      loop: "{{ result.ovirt_nics }}"
#      when: result.ovirt_nics is defined and result.ovirt_nics | length > 0
#    - name: Reboot the VM to apply network changes
#      ovirt_vm:
#        auth: "{{ ovirt_auth }}"
#        state: running
#        name: olam_dep_net
